# Generated by Django 5.1.6 on 2025-02-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_servicio_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_hora',
        ),
    ]
