# Generated by Django 5.1.6 on 2025-02-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_rename_fecha_reserva_reserva_fecha_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='precio',
            new_name='precio_base',
        ),
    ]
