# Generated by Django 5.1.6 on 2025-02-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_rename_precio_servicio_precio_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre',
            new_name='servicio_nombre',
        ),
    ]
