# Generated by Django 5.1.6 on 2025-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_rename_nombre_servicio_servicio_nombre'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'servicio', 'fecha_hora'), name='unique_reserva'),
        ),
    ]
