# Generated by Django 5.1.6 on 2025-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_reserva_unique_reserva'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio_base',
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('email', 'servicio', 'fecha_hora'), name='unique_reserva'),
        ),
    ]
