# Generated by Django 5.1.6 on 2025-02-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0007_remove_reserva_unique_reserva_remove_reserva_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='email',
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'servicio', 'fecha_hora'), name='unique_reserva'),
        ),
    ]
