# Generated by Django 5.1.6 on 2025-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0009_alter_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ciudad',
            field=models.CharField(default='Desconocida', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_celular',
            field=models.CharField(default='Sin número', max_length=15),
            preserve_default=False,
        ),
    ]
