# Generated by Django 5.1.6 on 2025-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0012_remove_producto_opciones_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
