# Generated by Django 5.1.6 on 2025-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0014_remove_opcionproducto_precio_extra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionproducto',
            options={'verbose_name': 'Opción de producto', 'verbose_name_plural': 'Opciones de productos'},
        ),
        migrations.AddField(
            model_name='opcionproducto',
            name='opciones',
            field=models.JSONField(default=list),
        ),
    ]
