# Generated by Django 5.1.6 on 2025-03-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0015_alter_opcionproducto_options_opcionproducto_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
