# Generated by Django 5.1.6 on 2025-03-04 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0016_itemcarrito_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
