# Generated by Django 5.1.6 on 2025-03-04 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0017_pedido_fecha_agregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_agregado',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
