# Generated by Django 5.1.6 on 2025-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0020_historialcompra_historialreserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'ordering': ['-fecha_agregado']},
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
