# Generated by Django 5.1.6 on 2025-04-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0024_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva',
        ),
    ]
