# Generated by Django 5.1.6 on 2025-03-27 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_nuevo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.SlugField(help_text='Código único para identificar este método (ej: visa, mastercard, transferencia)', unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o instrucciones para este método de pago')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen logo del método de pago', null=True, upload_to='metodos_pago/')),
                ('imagen_path', models.CharField(blank=True, help_text='Alternativamente, ruta al archivo SVG estático (ej: carrito_nuevo/img/visa.svg)', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización')),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Establecer como método de pago predeterminado')),
                ('requiere_tarjeta', models.BooleanField(default=False, help_text='Este método requiere datos de tarjeta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito_nuevo.metodopago'),
        ),
    ]
