# Generated by Django 5.1.6 on 2025-03-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_nuevo', '0002_metodopago_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='codigo_qr',
            field=models.ImageField(blank=True, help_text='Código QR para este método de pago', null=True, upload_to='metodos_pago/qr/'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='contenido_html',
            field=models.TextField(blank=True, help_text='Contenido HTML personalizado para la página de confirmación. Puedes usar {{ pedido.total_formateado }}, {{ pedido.id }}, etc.'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Cualquier información adicional para mostrar en la confirmación'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='instrucciones_confirmacion',
            field=models.TextField(blank=True, help_text='Instrucciones detalladas que aparecerán en la página de confirmación'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='telefono_contacto',
            field=models.CharField(blank=True, help_text='Número telefónico asociado a este método de pago', max_length=100),
        ),
    ]
